//
//  AssetsIcon.swift
//  Airlyhub
//
//  Created by Le Ha Gia Bao on 27/12/2025.
//

import UIKit

struct AssetsIcon {
    static let exploreActive = UIImage(named: "ExploreActive")
    static let exploreInactive = UIImage(named: "ExploreInactive")
    static let flightsActive = UIImage(named: "FlightsActive")
    static let flightsInactive = UIImage(named: "FlightsInactive")
    static let favoritesActive = UIImage(named: "FavoritesActive")
    static let favoritesInactive = UIImage(named: "FavoritesInactive")
    static let profileActive = UIImage(named: "ProfileActive")
    static let profileInactive = UIImage(named: "ProfileInactive")

    static let plane = UIImage(named: "airplane")
    static let wifi = UIImage(named: "wifi")
    static let notifications = UIImage(named: "notifications")
    static let tickets = UIImage(named: "tickets")
    static let cards = UIImage(named: "cards")
    static let services = UIImage(named: "services")
    static let setting = UIImage(named: "setting")
    static let logout = UIImage(named: "logout")
    static let arrowLeft = UIImage(named: "arrowLeft")
    static let map = UIImage(named: "map")
    static let doubleArrow = UIImage(named: "doubleArrow")
    static let calendar = UIImage(named: "calendar")
    static let smileyWink = UIImage(named: "smileyWink")
    static let minus = UIImage(named: "minus")
    static let plus = UIImage(named: "plus")
    static let xcircle = UIImage(named: "xcircle")
    static let search = UIImage(named: "search")
    static let location = UIImage(named: "location")
    static let earth = UIImage(named: "earth")
    static let badge = UIImage(named: "badge")
    static let blueAirplane = UIImage(named: "blueAirplane")
    static let pencil = UIImage(named: "pencil")
    static let payment = UIImage(named: "payment")
    static let mapFlight = UIImage(named: "mapFlight")
    static let slider = UIImage(named: "slider")

    static var logo: UIImage? {
        switch AppConfig.environment {
        case .dev: return UIImage(named: "logoDev")
        case .stg: return UIImage(named: "logoStg")
        case .prod: return UIImage(named: "logo")
        }
    }

    static let notiFlight = UIImage(named: "notiFlight")
    static let notiCancel = UIImage(named: "notiCancel")
    static let notiRefund = UIImage(named: "notiRefund")
    static let notiWelcome = UIImage(named: "notiWelcome")

    static let alipay = UIImage(named: "alipay")
    static let americanExpress = UIImage(named: "americanexpress")
    static let applePay = UIImage(named: "applepay")
    static let belcart = UIImage(named: "belcart")
    static let bitcoin = UIImage(named: "bitcoin")
    static let bitpay = UIImage(named: "bitpay")
    static let dankort = UIImage(named: "dankort")
    static let dash = UIImage(named: "dash")
    static let dinersClub = UIImage(named: "dinersclub")
    static let discover = UIImage(named: "discover")
    static let elo = UIImage(named: "elo")
    static let ethereum = UIImage(named: "ethereum")
    static let forbrugsforeningen = UIImage(named: "forbrugsforeningen")
    static let giropay = UIImage(named: "giropay")
    static let googlePay = UIImage(named: "googlepay")
    static let hiper = UIImage(named: "hiper")
    static let hipercard = UIImage(named: "hipercard")
    static let ideal = UIImage(named: "ideal")
    static let jcb = UIImage(named: "jcb")
    static let klarna = UIImage(named: "klarna")
    static let litecoin = UIImage(named: "litecoin")
    static let maestro = UIImage(named: "maestro")
    static let mastercard = UIImage(named: "mastercard")
    static let mastercardSecureCode = UIImage(named: "mastercardsecurecode")
    static let mir = UIImage(named: "mir")
    static let monero = UIImage(named: "monero")
    static let paykeeper = UIImage(named: "paykeeper")
    static let paypal = UIImage(named: "paypal")
    static let paypalFull = UIImage(named: "paypalfull")
    static let paypass = UIImage(named: "paypass")
    static let qiwi = UIImage(named: "qiwi")
    static let ripple = UIImage(named: "ripple")
    static let robokassa = UIImage(named: "robokassa")
    static let ruble = UIImage(named: "ruble")
    static let sagepay = UIImage(named: "sagepay")
    static let sodexo = UIImage(named: "sodexo")
    static let troy = UIImage(named: "troy")
    static let uatp = UIImage(named: "uatp")
    static let unionPay = UIImage(named: "unionpay")
    static let visa = UIImage(named: "visa")
    static let visaVerified = UIImage(named: "visaverified")
    static let vorkasse = UIImage(named: "vorkasse")
    static let webmoney = UIImage(named: "webmoney")
    static let westernUnion = UIImage(named: "westernunion")
    static let yandex = UIImage(named: "yandex")
    static let yapper = UIImage(named: "yapper")
    static let yoco = UIImage(named: "yoco")
}
